apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: team3-ns
  labels:
    app: admin-service

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: admin-service

  template:
    metadata:
      labels:
        app: admin-service

    spec:
      containers:
        - name: admin-service
          image: team3kubectl/admin-service:v1.1.1
          imagePullPolicy: Always

          ports:
            - containerPort: 8008

          envFrom:
            - configMapRef:
                name: admin-config
            - secretRef:
                name: admin-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 8008
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8008
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3