apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: team3-ns
spec:
  selector:
    app: notification
  ports:
  - port: 80
    targetPort: 8006 # Corrected: Now matches containerPort
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-configmap
  namespace: team3-ns
data:
  PORT: "8006"
  REDIS_HOST: notification-redis
  REDIS_PORT: "6379"
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: team3-ns
type: Opaque
data:
  RABBITMQ_USER: Z3Vlc3Q=
  RABBITMQ_PASSWORD: Z3Vlc3Q=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: team3-ns
spec:
  selector:
    matchLabels:
      app: notification
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification-container
        image: team3kubectl/notification-service:v1.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8006
        envFrom:
        - configMapRef:
            name: notification-configmap
        - secretRef:
            name: notification-secret
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"