{{- if .Values.services.payment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.services.payment.replicas }}
  {{- if .Values.services.payment.minReadySeconds }}
  minReadySeconds: {{ .Values.services.payment.minReadySeconds }}
  {{- end }}
  strategy:
    type: {{ .Values.services.payment.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.services.payment.strategy.maxUnavailable | quote }}
      maxSurge: {{ .Values.services.payment.strategy.maxSurge | quote }}
  selector:
    matchLabels:
      app: payment-deploy
  template:
    metadata:
      labels:
        app: payment-deploy
    spec:
      {{- if .Values.services.payment.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.services.payment.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
        - name: payment-deploy
          image: {{ .Values.services.payment.image }}
          imagePullPolicy: {{ .Values.services.payment.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.services.payment.port }}
          envFrom:
            - configMapRef:
                name: payment-configmap
            - secretRef:
                name: payment-secret
          resources:
            requests:
              cpu: {{ .Values.services.payment.resources.requests.cpu | quote }}
              memory: {{ .Values.services.payment.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.services.payment.resources.limits.cpu | quote }}
              memory: {{ .Values.services.payment.resources.limits.memory | quote }}
          {{- if .Values.services.payment.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.services.payment.probes.readiness.path }}
              port: {{ .Values.services.payment.port }}
            initialDelaySeconds: {{ .Values.services.payment.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.services.payment.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.services.payment.probes.readiness.failureThreshold }}
          {{- end }}
          {{- if .Values.services.payment.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.services.payment.probes.liveness.path }}
              port: {{ .Values.services.payment.port }}
            initialDelaySeconds: {{ .Values.services.payment.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.services.payment.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.services.payment.probes.liveness.failureThreshold }}
          {{- end }}
{{- end }}
