{{- if .Values.services.payment.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: payment-deploy
  ports:
    - protocol: TCP
      port: {{ .Values.services.payment.port }}
      targetPort: {{ .Values.services.payment.port }}
{{- end }}
