apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: team3-ns
data:
  init-db.sh: |
    #!/bin/bash
    set -e

    create_databases() {
        local database=$1
        echo "Creating database '$database'"
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
            CREATE DATABASE $database;
    EOSQL
    }

    if [ -n "$POSTGRES_MULTIPLE_DATABASES" ]; then
        echo "Creating multiple databases: $POSTGRES_MULTIPLE_DATABASES"
        for db in $(echo $POSTGRES_MULTIPLE_DATABASES | tr ',' ' '); do
            create_databases $db
        done
    fi