apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: team3-ns
spec:
  selector:
    app: notification
  ports:
  - port: {{ .Values.notification.service.port }}
    targetPort: {{ .Values.notification.service.port }}
  type: {{ .Values.notification.service.type }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-configmap
  namespace: team3-ns
data:
  PORT: {{ .Values.notification.env.port | quote }}
  REDIS_HOST: {{ .Values.notification.env.redisHost | quote }}
  REDIS_PORT: {{ .Values.notification.env.redisPort | quote }}
  RABBITMQ_HOST: {{ .Values.notification.env.rabbitmqHost | quote }}
  RABBITMQ_PORT: {{ .Values.notification.env.rabbitmqPort | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: team3-ns
type: Opaque
stringData:
  RABBITMQ_USER: {{ .Values.notification.secrets.rabbitmqUser | quote }}
  RABBITMQ_PASSWORD: {{ .Values.notification.secrets.rabbitmqPassword | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: team3-ns
spec:
  selector:
    matchLabels:
      app: notification
  replicas: {{ .Values.notification.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification-container
        image: "{{ .Values.notification.image.repository }}:{{ .Values.notification.image.tag }}"
        imagePullPolicy: {{ .Values.notification.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.notification.service.port }}
        envFrom:
        - configMapRef:
            name: notification-configmap
        - secretRef:
            name: notification-secret
        resources:
          requests:
            cpu: {{ .Values.notification.resources.requests.cpu | quote }}
            memory: {{ .Values.notification.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.notification.resources.limits.cpu | quote }}
            memory: {{ .Values.notification.resources.limits.memory | quote }}
