apiVersion:  storage.k8s.io/v1
kind:  StorageClass
metadata:
  name:  mongo-storageclass
  namespace: team3-ns
provisioner:  nfs.csi.k8s.io
parameters:
  server:  15.206.94.46  
  share:  /var/nfs/general
volumeBindingMode:  Immediate