{{- if .Values.storage }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.className }}
  namespace: {{ .Values.global.namespace }}
provisioner: {{ .Values.storage.provisioner }}
{{- if .Values.storage.nfs }}
parameters:
  server: {{ .Values.storage.nfs.server }}
  share: {{ .Values.storage.nfs.share }}
{{- end }}
{{- if .Values.storage.volumeBindingMode }}
volumeBindingMode: {{ .Values.storage.volumeBindingMode }}
{{- end }}
{{- end }}
