apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-deployment
  namespace: team3-ns
  labels:
    app: events-service
spec:
  replicas: {{ .Values.events.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: events-service
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
        - name: events-service
          image: "{{ .Values.events.image.repository }}:{{ .Values.events.image.tag }}"
          imagePullPolicy: {{ .Values.events.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.events.service.port }}
          envFrom:
            - configMapRef:
                name: events-config
            - secretRef:
                name: events-secret
          resources:
            requests:
              cpu: {{ .Values.events.resources.requests.cpu | quote }}
              memory: {{ .Values.events.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.events.resources.limits.cpu | quote }}
              memory: {{ .Values.events.resources.limits.memory | quote }}
          startupProbe:
            httpGet:
              path: {{ .Values.events.probes.startup.path }}
              port: {{ .Values.events.service.port }}
            initialDelaySeconds: {{ .Values.events.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.events.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.events.probes.startup.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.events.probes.readiness.path }}
              port: {{ .Values.events.service.port }}
            initialDelaySeconds: {{ .Values.events.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.events.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.events.probes.liveness.path }}
              port: {{ .Values.events.service.port }}
            initialDelaySeconds: {{ .Values.events.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.events.probes.liveness.periodSeconds }}