apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: team3-ns
spec:
  type: {{ .Values.events.service.type }}
  selector:
    app: events-service
  ports:
    - port: {{ .Values.events.service.port }}
      targetPort: {{ .Values.events.service.port }}