apiVersion: v1
kind: ConfigMap
metadata:
  name: events-config
  namespace: team3-ns
data:
  PORT: {{ .Values.events.env.port | quote }}
  MONGO_HOST: {{ .Values.events.env.mongoHost | quote }}
  MONGO_PORT: {{ .Values.events.env.mongoPort | quote }}
  MONGO_DB: {{ .Values.events.env.mongoDb | quote }}
  MONGO_URI: {{ .Values.events.env.mongoUri | quote }}