{{- if .Values.services.users.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: users-service
  ports:
    - port: {{ .Values.services.users.port }}
      targetPort: {{ .Values.services.users.port }}
      protocol: TCP
  type: ClusterIP
{{- end }}
