{{- if .Values.infrastructure.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.infrastructure.rabbitmq.port }}
      targetPort: {{ .Values.infrastructure.rabbitmq.port }}
    - name: management
      port: {{ .Values.infrastructure.rabbitmq.managementPort }}
      targetPort: {{ .Values.infrastructure.rabbitmq.managementPort }}
  type: {{ .Values.infrastructure.rabbitmq.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.infrastructure.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.infrastructure.rabbitmq.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.infrastructure.rabbitmq.port }}
            - containerPort: {{ .Values.infrastructure.rabbitmq.managementPort }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.infrastructure.rabbitmq.secrets.username | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.infrastructure.rabbitmq.secrets.password | quote }}
          resources:
            requests:
              memory: {{ .Values.infrastructure.rabbitmq.resources.requests.memory | quote }}
              cpu: {{ .Values.infrastructure.rabbitmq.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.infrastructure.rabbitmq.resources.limits.memory | quote }}
              cpu: {{ .Values.infrastructure.rabbitmq.resources.limits.cpu | quote }}
{{- end }}
