{{- if .Values.databases.mongodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.databases.mongodb.secrets.root_username | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.databases.mongodb.secrets.root_password | b64enc }}
{{- end }}
