apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-deployment
  namespace: team3-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
        - name: ticket-container
          image: team3kubectl/ticket-service:v1.1.1
          ports:
            - containerPort: 8005
          envFrom:
            - configMapRef:
                name: ticket-config
            - secretRef:
                name: ticket-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
