apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: team3-ns
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: payment-deploy
  template:
    metadata:
      labels:
        app: payment-deploy
    spec:
      containers:
        - name: payment-deploy
          image: team3kubectl/payment-service:v1.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8004
          envFrom:
            - configMapRef:
                name: payment-configmap
            - secretRef:
                name: payment-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 20
            periodSeconds: 10