{{- if .Values.databases.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: {{ .Values.global.namespace }}
spec:
  serviceName: postgres-db
  replicas: {{ .Values.databases.postgres.replicas }}
  minReadySeconds: 10
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: postgres
          image: {{ .Values.databases.postgres.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.databases.postgres.port }}
          resources:
            requests:
              cpu: {{ .Values.databases.postgres.resources.requests.cpu | quote }}
              memory: {{ .Values.databases.postgres.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.databases.postgres.resources.limits.cpu | quote }}
              memory: {{ .Values.databases.postgres.resources.limits.memory | quote }}
          envFrom:
            - configMapRef:
                name: postgres-configmap
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-script
          configMap:
            name: postgres-init-script
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: team3-storageclass
        resources:
          requests:
            storage: {{ .Values.databases.postgres.storage }}
{{- end }}
