{{- if .Values.infrastructure.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.infrastructure.postgres.secrets.db_user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.infrastructure.postgres.secrets.db_password | b64enc }}
{{- end }}
