{{- if .Values.databases.postgres.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: {{ .Values.global.namespace }}
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "admin"
  POSTGRES_MULTIPLE_DATABASES: "payment_db,booking_db,ticket_db,events_db,users_db"
  PGDATA: "/var/lib/postgresql/data/pgdata"
{{- end }}
