{{- if .Values.databases.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: {{ .Values.global.namespace }}
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: {{ .Values.databases.postgres.port }}
      targetPort: {{ .Values.databases.postgres.port }}
{{- end }}
