apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-configmap
  namespace: team3-ns
data:
  PORT: "8004"

  DB_HOST: "postgres-db"
  DB_PORT: "5432"
  DB_NAME: "payment_db"

  BOOKING_SERVICE_URL: "http://booking-service:8003"
  TICKET_SERVICE_URL: "http://ticket-service:8005"