apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: team3-ns
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASSWORD: YWRtaW5wYXNz

  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: YWRtaW5wYXNz