apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: payment-storageclass
provisioner: nfs.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  server: <IP_ADDRESS>
  share: /exported/path