{{- if .Values.services.ticket.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-config
  namespace: {{ .Values.global.namespace }}
data:
  {{- range $key, $value := .Values.services.ticket.env }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}
