{{- if .Values.services.ticket.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ticket-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.services.ticket.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
