apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-config
  namespace: team3-ns
data:
  PORT: "8003"
  DB_HOST: "postgres-db"
  DB_PORT: "5432"
  DB_NAME: "booking_db"
  EVENTS_SERVICE_URL: "http://events-service:8002"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
