apiVersion: v1
kind: Secret
metadata:
  name: booking-secret
  namespace: team3-ns 
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASSWORD: YWRtaW5wYXNz 
  RABBITMQ_USER: Z3Vlc3Q=
  RABBITMQ_PASSWORD: Z3Vlc3Q=
